### ISSUE TITLE
Should have non-modal Reply box

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#30] opened 2016-03-24 04:55 UTC
In Topics, when I click reply I get a big edit box that invites me to type in my reply.

PROBLEM: I can't move or resize the edit box & the edit box prevents me from seeing what I'm replying to. What I often happens is that I start to write my reply and then realize I want to refer to the exact wording of the message I'm replying to. So, I have to save as draft, look at the message, then open the draft to keep typing. Sometimes I have to do it more than once.  

Would be much easier if I could resize &/or move the Reply box so I could see the source message I'm replying to.

**Comment by agilepro** [comment] 2016-04-03 22:50
Yeah, I Agree.  I originally coded that way, but it got to be too complicated to keep track of the state, and there were corner conditions that could cause you to lose work.  Need to reconsider doing this correctly in an updated UI.

**Comment by agilepro** [comment] 2017-12-14 18:05
duplicate of another

**Closed by agilepro** 2017-12-14 18:05 UTC
