### ISSUE TITLE
can't do invite

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#342] opened 2019-03-13 13:00 UTC
if I try to do an end run and just invite the person, I get this message

![image](https://user-images.githubusercontent.com/10082365/54280709-7dc08980-456e-11e9-9f77-8f01d8ca8a37.png)

**Comment by agilepro** [comment] 2019-03-13 15:20
In viewing the log file, this error #342 was caused by the last problem #341.  The thread tid=18 somehow got blocked when trying to add Daniel King to the role.   That locked the workspace, and then caused this error because the workspace was locked for 30+ seconds and this operation only waits 10 seconds for the lock to clear.   Have to identify why the thread 18 got stuck locking the file, however I am going to close this issue because it does not add any more information.

**Closed by agilepro** 2019-03-13 15:20 UTC
