### ISSUE TITLE
members list not responsive

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#128] opened 2016-11-15 03:13 UTC
I am trying to add members to the Weaver Tutorials workspace. There are 33 members shown (33 icons). However, when I clicked on the Members icons, the system would not let me add another member. Now, the left side still shows the icons, but the menu on the right shows no names at all. I tried adding the same name to Weaver Sandbox, and there was no problem. So, perhaps the problem is localized to that one workspace.

**Comment by agilepro** [comment] 2016-11-26 07:11
The problem is that there is a duplicate in the list.   The widget that si being used there does not like duplicates in the list ... it's bookkeeping gets messed up.  You are not supposed to be able to do this.  If you try, you will find you can't.  However, if people are added in one form, and then they edit and change their email address or something it is possible.

I will add some code to clean out the duplicates just before display to resolve this problem.

**Comment by agilepro** [comment] 2016-11-29 00:25
Fix that cleans up the user list has been checked in and the server is updated

**Closed by agilepro** 2016-11-29 00:25 UTC
