### ISSUE TITLE
blocked from joining

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#174] opened 2017-04-25 15:49 UTC
Received an invite to join a Galgael site circle. filled out name and password. Got the following message:

![image](https://cloud.githubusercontent.com/assets/10082365/25394886/4d0fc686-29ad-11e7-834b-1cae79e9d61d.png)

**Comment by agilepro** [comment] 2017-04-27 03:01
Excellent.  This is a real reproducible bug.  The problem was INVITING someone to a SITE.  We had always invited people to workspaces before.  The page for roles is the same between workspace and sites, but this invite function needs to be a little different in the two cases.  So ... now fixed and should be available in a few days.

**Closed by agilepro** 2017-04-27 03:01 UTC
